# Generated by Django 5.2.4 on 2025-07-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo del pasajero', max_length=100)),
                ('apellido', models.CharField(help_text='Apellido completo del pasajero', max_length=100)),
                ('documento', models.CharField(help_text='Número de documento de identidad (DNI, pasaporte, etc.)', max_length=20, unique=True)),
                ('email', models.EmailField(help_text='Dirección de correo electrónico del pasajero', max_length=254)),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono del pasajero', max_length=15, null=True)),
                ('fecha_nacimiento', models.DateField(help_text='Fecha de nacimiento del pasajero')),
                ('direccion', models.TextField(blank=True, help_text='Dirección completa del pasajero', null=True)),
            ],
            options={
                'verbose_name': 'Pasajero',
                'verbose_name_plural': 'Pasajeros',
                'db_table': 'pasajeros',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
