# Generated by Django 5.2.4 on 2025-07-27 18:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pasajeros', '0001_initial'),
        ('vuelos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_reserva', models.CharField(default=uuid.uuid4, help_text='Código único de la reserva', max_length=10, unique=True)),
                ('estado', models.CharField(choices=[('confirmada', 'Confirmada'), ('pendiente', 'Pendiente de Pago'), ('cancelada', 'Cancelada'), ('completada', 'Completada'), ('expirada', 'Expirada')], default='pendiente', help_text='Estado actual de la reserva', max_length=20)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se realizó la reserva')),
                ('fecha_vencimiento', models.DateTimeField(help_text='Fecha límite para confirmar la reserva')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio final de la reserva', max_digits=10)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre la reserva', null=True)),
                ('asiento', models.ForeignKey(help_text='Asiento reservado', on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='vuelos.asiento')),
                ('pasajero', models.ForeignKey(help_text='Pasajero que realiza la reserva', on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='pasajeros.pasajero')),
                ('vuelo', models.ForeignKey(help_text='Vuelo reservado', on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='vuelos.vuelo')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reservas',
                'ordering': ['-fecha_reserva'],
                'unique_together': {('vuelo', 'pasajero', 'asiento')},
            },
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barra', models.CharField(help_text='Código de barras único del boleto', max_length=50, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de emisión del boleto')),
                ('estado', models.CharField(choices=[('emitido', 'Emitido'), ('usado', 'Usado'), ('cancelado', 'Cancelado'), ('perdido', 'Perdido')], default='emitido', help_text='Estado actual del boleto', max_length=20)),
                ('puerta_embarque', models.CharField(blank=True, help_text='Puerta de embarque asignada', max_length=10, null=True)),
                ('hora_embarque', models.TimeField(blank=True, help_text='Hora de embarque', null=True)),
                ('reserva', models.OneToOneField(help_text='Reserva asociada a este boleto', on_delete=django.db.models.deletion.CASCADE, related_name='boleto', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
                'db_table': 'boletos',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
