# Generated by Django 5.2.4 on 2025-07-27 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(help_text='Modelo del avión (ej: Boeing 737, Airbus A320)', max_length=100)),
                ('capacidad', models.PositiveIntegerField(help_text='Número total de asientos en el avión')),
                ('filas', models.PositiveIntegerField(help_text='Número de filas de asientos')),
                ('columnas', models.PositiveIntegerField(help_text='Número de columnas de asientos')),
            ],
            options={
                'verbose_name': 'Avión',
                'verbose_name_plural': 'Aviones',
                'db_table': 'aviones',
                'ordering': ['modelo'],
            },
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(help_text='Ciudad y aeropuerto de origen', max_length=100)),
                ('destino', models.CharField(help_text='Ciudad y aeropuerto de destino', max_length=100)),
                ('fecha_salida', models.DateTimeField(help_text='Fecha y hora de salida del vuelo')),
                ('fecha_llegada', models.DateTimeField(help_text='Fecha y hora de llegada del vuelo')),
                ('duracion', models.PositiveIntegerField(help_text='Duración del vuelo en minutos')),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('abordando', 'Abordando'), ('en_vuelo', 'En Vuelo'), ('aterrizado', 'Aterrizado'), ('cancelado', 'Cancelado'), ('retrasado', 'Retrasado')], default='programado', help_text='Estado actual del vuelo', max_length=20)),
                ('precio_base', models.DecimalField(decimal_places=2, help_text='Precio base del boleto', max_digits=10)),
                ('avion', models.ForeignKey(help_text='Avión asignado para este vuelo', on_delete=django.db.models.deletion.CASCADE, related_name='vuelos', to='vuelos.avion')),
            ],
            options={
                'verbose_name': 'Vuelo',
                'verbose_name_plural': 'Vuelos',
                'db_table': 'vuelos',
                'ordering': ['fecha_salida'],
            },
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número único del asiento (ej: A1, B3, C12)', max_length=10, unique=True)),
                ('fila', models.PositiveIntegerField(help_text='Número de fila del asiento')),
                ('columna', models.CharField(help_text='Letra de la columna (ej: A, B, C)', max_length=2)),
                ('tipo', models.CharField(choices=[('economica', 'Económica'), ('premium', 'Premium'), ('primera', 'Primera Clase'), ('emergencia', 'Salida de Emergencia')], default='economica', help_text='Tipo de asiento', max_length=20)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('reservado', 'Reservado'), ('mantenimiento', 'En Mantenimiento')], default='disponible', help_text='Estado actual del asiento', max_length=20)),
                ('avion', models.ForeignKey(help_text='Avión al que pertenece este asiento', on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='vuelos.avion')),
            ],
            options={
                'verbose_name': 'Asiento',
                'verbose_name_plural': 'Asientos',
                'db_table': 'asientos',
                'ordering': ['avion', 'fila', 'columna'],
                'unique_together': {('avion', 'fila', 'columna')},
            },
        ),
    ]
